services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - api

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${API_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD:-example}
      POSTGRES_DB: ${API_DB_NAME:-snakesite}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
