version: '3.8'

services:
  front:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    image: shashaevkirill/snakesite
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data:
