
events {}

http {
    types {
        text/html html;
        text/css css;
    }

    server {
        listen 0.0.0.0:8089;
        server_name base.com;
        root D:\my\google_drive\singles\folders\Projects\Frontend\WEB-development;
        index index.html;

        location = /main {
            return 200 'Hello word!';
        }

        location ^~ /1234 {
            return 200 1234;
        }

        location /1 {
            return 200 1;
        }

        location /12 {
            return 200 2;
        }

        location /123 {
            return 200 3;
        }

        # location ~ b {
        #     return 200 bbb; 
        # }

        # location ~ a {
        #     return 200 aaa;
        # }

        # location ~ 3 {
        #     return 200 333;
        # }

        # location /sss { # Эффект присутствия
        #     return 200 'sss';
        # }

        # location ^~ /ss {
        #     return 200 'ss';
        # }

        # location ~ ss {
        #     return 200 's';
        # }
    }
}
